### ISSUE TITLE
Создать архитектуру проекта + config

### ISSUE THREAD

**Issue by alexseipopov** [s21platform/friends-service#1]
Предлагаю создать проект локально (go mod init), после прикрепить remote URL (git remote add origin https://github.com/s21platform/friends-service.git). Эта таска предполагает создание структуры проекта: по факту создание main.go в cmd/service/ и чтение необходимых environments из .env файла из корня проекта
Пример чтения переменных окружения можно посмотреть в сервисe [auth-service](https://github.com/s21platform/auth-service/blob/main/internal/config/config.go)
Запушить это в main ветку

Файл .env сразу необходимо добавить в .gitignore

**Comment by aleksakokorewa** [comment]
Создано cmd/service/main.go, internal/config/config.go, написано чтение env
Запушено в main
